spring:
  application:
    name: ecommerce

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db
    username: root
    password: 6174@Adarsha
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

jwt:
  secret: MySecretKeyForEcommerceApplicationThatIsAtLeast32CharactersLongForJWTTokens
  expiration: 86400000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha

logging:
  level:
    root: INFO
    com.example.ecommerce: DEBUG